version: '3'
services:
  mysqldb:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: insight
      MYSQL_DATABASE: shorturl
      MYSQL_USER: insight
      MYSQL_PASSWORD: insight
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    command:
      - "--web.enable-lifecycle"
    restart: always
    user: root

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana-volume:/var/lib/grafana
    restart: always
    networks:
      - promnet
    ports:
      - 3030:3000
    user: root

volumes:
  db_data:
  redis_data:

networks:
  promnet:
    driver: bridge
